### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by VytalyGorbatov** [ITA-Dnipro/BackEndMonitoring#3]
Can be implemented in 2 ways:
1) using mutexes;
2) using critical sections(check UNIX realization)

**Comment by Chupakabra0** [comment]
1. Create thread-safe logger, using mutex;
2. Logger must display messages at several levels of logging in several output streams;
3. Message of logger must have different special info such as “line number”, “filename”, etc. Also it can have different amount of variables. If it is, output must have var’s name and var’s value;
4. Logger must be cross platform dynamic library.
